* what is category theory?

category theory sits at the center of contemporary mathematics, yet
stays obscure and is considered esoteric even by mathematicians.

it studies everything by their interactions, or rather, their actions.
it studies the abstract concretly, the rational empirically, and
allows you to abstract without loss.

* how does it help me?  i am a

** programmer

to understand functional programming.  lambda calculus?  that's just
one cartesian closed category.

to understand logical programming.  by understand i mean UNDERSTAND.

to understand imperative programming.  that it is wrong.

https://philipnilsson.github.io/Badness10k/escaping-hell-with-monads/

** scientist

to understand the scientific method and the language of science.

to understand intelligence, consciousness, and emergence in general.

http://www.j-paine.org/dobbs/why_be_interested_in_categories.html

** artist

to understand creativity, mathematically and mechanically.

** occultist

to understand the work of the sun and the secret fire that burns at
the heart of the world.

** philosopher

get a life.

* give me something real, alright?

** Eugenia Cheng "Category Theory in Life"

a light introduction with applications in real life.

https://www.youtube.com/watch?v=ho7oagHeqNc

** Robb Seaton "Why Category Theory Matters"

an overview with links of applications.

http://rs.io/why-category-theory-matters/
