#+TITLE: emacs setup
#+AUTHOR: ysmiraak

* load
make =user-init-file= like this.
#+BEGIN_SRC emacs-lisp :tangle no
  (package-initialize)
  (org-babel-load-file (expand-file-name "setup.org" user-emacs-directory))
#+END_SRC
or this for tangled setup.
#+BEGIN_SRC emacs-lisp :tangle no
  (package-initialize)
  (load-file (expand-file-name "setup.el" user-emacs-directory))
#+END_SRC
* library
#+BEGIN_SRC emacs-lisp
  (push '("melpa" . "http://melpa.org/packages/") package-archives)
  (customize-set-variable
   'package-selected-packages
   '(s f dash dash-functional suggest bind-key delight
       benchmark-init exec-path-from-shell
       zenburn-theme powerline rainbow-delimiters
       counsel flx smex which-key magit projectile avy ace-window centered-cursor-mode
       undo-tree browse-kill-ring zzz-to-char fix-word vimish-fold drag-stuff
       aggressive-indent hungry-delete whitespace-cleanup-mode
       smartparens multiple-cursors visual-regexp expand-region region-bindings-mode
       company company-quickhelp yasnippet flycheck flycheck-pos-tip
       clojure-mode cider clj-refactor kibit-helper geiser ediprolog haskell-mode idris-mode
       rust-mode cargo flycheck-rust racer elpy js2-mode rainbow-mode
       ess csv-mode markdown-mode latex-preview-pane cdlatex company-auctex))
#+END_SRC
or use the stable versions.
#+BEGIN_SRC emacs-lisp :tangle no
  (push '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/") package-archives)
#+END_SRC
to install the packages above, change =:tangle no= to =:tangle yes= below, or manually execute the commands.
#+BEGIN_SRC emacs-lisp :tangle no
  (package-refresh-contents)
  (package-install-selected-packages)
#+END_SRC
bench when necessary.
#+BEGIN_SRC emacs-lisp :tangle no
  (benchmark-init/activate)
#+END_SRC
* elisp
#+BEGIN_SRC emacs-lisp
  (require 's)
  (require 'f)
  (require 'dash)
  (require 'dash-functional)
  (dash-enable-font-lock)

  (require 'bind-key)
  (bind-keys ("M-Q" . suggest)
             :map lisp-mode-shared-map
             ("M-RET" . eval-last-sexp)
             ("C-M-x" . eval-defun)
             ("C-M-z" . eval-region))

  (require 'delight)
  (delight 'eldoc-mode nil 'eldoc)
  (-each '(emacs-lisp-mode-hook lisp-interaction-mode-hook ielm-mode-hook)
    (-rpartial #'add-hook #'eldoc-mode))

  (defun unbind-keys (m &rest ks)
    (--each ks (unbind-key it m)))

  (defun add-hooks (h &rest fs)
    (-each fs (-partial #'add-hook h)))

  (defun cset (&rest sym-vals)
    (-each (-partition-all 2 sym-vals)
      (-applify #'customize-set-variable)))
#+END_SRC
* system
prevent custom from editing my files.
#+BEGIN_SRC emacs-lisp
  (cset 'custom-file (f-expand "custom.el" user-emacs-directory))
#+END_SRC
backup.
#+BEGIN_SRC emacs-lisp
  (cset 'create-lockfiles       nil
        'auto-save-default      nil
        'version-control        t
        'delete-old-versions    t
        'backup-directory-alist `(("." . ,temporary-file-directory)))
#+END_SRC
clipboard.
#+BEGIN_SRC emacs-lisp
  (cset 'select-enable-clipboard             t
        'save-interprogram-paste-before-kill t)
#+END_SRC
for mac.
#+BEGIN_SRC emacs-lisp
  (when (equal 'ns window-system)
    (toggle-frame-fullscreen)
    (bind-keys ("<C-s-f>" . toggle-frame-fullscreen) ("<C-s-268632070>" . toggle-frame-fullscreen))
    (cset 'insert-directory-program "gls")
    (exec-path-from-shell-initialize)
    (exec-path-from-shell-copy-envs '("PATH" "LANG" "LC_ALL" "EMAIL")))
#+END_SRC
enable some disabled commands.
#+BEGIN_SRC emacs-lisp
  (-each '(upcase-region
           downcase-region
           narrow-to-region
           dired-find-alternate-file)
    (-cut put <> 'disabled nil))
#+END_SRC
* theme
simpler style.
#+BEGIN_SRC emacs-lisp
  (cset 'uniquify-buffer-name-style 'forward
        'inhibit-startup-screen     t
        'initial-scratch-message    nil
        'tool-bar-mode              nil
        'scroll-bar-mode            nil
        'column-number-mode         t
        'ring-bell-function         'ignore)
#+END_SRC
save me some typing.
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
fancier face on graphic devices.
#+BEGIN_SRC emacs-lisp
  (when (display-graphic-p)
    (custom-set-faces
     '(region ((t (:background "#242424"))))
     '(cursor ((t (:background "#DAA520")))))
    (load-theme 'zenburn t)
    (global-hl-line-mode 1)
    (powerline-center-theme)
    (add-hooks 'prog-mode-hook #'rainbow-delimiters-mode-enable))
#+END_SRC
cursor.
#+BEGIN_SRC emacs-lisp
  (cset 'blink-cursor-mode              nil
        'cursor-type                    '(bar . 3)
        'cursor-in-non-selected-windows 'hollow)
#+END_SRC
never wrap lines.
#+BEGIN_SRC emacs-lisp
  (cset 'truncate-lines t)
  (bind-keys ("C-M-_" . toggle-truncate-lines)
             ("C-M--" . toggle-truncate-lines)
             ("M-#"   . linum-mode))
#+END_SRC
* navigation
within emacs.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("C-s" . swiper) ("M-x" . counsel-M-x))
  (ivy-mode 1)
  (delight 'ivy-mode nil 'ivy)
  (cset 'ivy-re-builders-alist '((read-file-name-internal . ivy--regex-ignore-order)
                                 (swiper                  . ivy--regex-plus)
                                 (t                       . ivy--regex-fuzzy))
        'ivy-height            13)

  (which-key-mode 1)
  (delight 'which-key-mode nil 'which-key)
#+END_SRC
among projects.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("M-G" . magit-status))

  (projectile-mode 1)
  (delight 'projectile-mode '(:eval (format " [%s]" (projectile-project-name))) 'projectile)
  (cset 'projectile-switch-project-action 'projectile-dired
        'projectile-completion-system     'ivy)
#+END_SRC
to jump around.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("M-'"     . avy-goto-char-2)
             ("M-\""    . avy-pop-mark)
             ("M-g g"   . avy-goto-line)
             ("M-g M-g" . avy-goto-line))

  (bind-keys ("C-x o" . ace-window))
#+END_SRC
for scrolling.
#+BEGIN_SRC emacs-lisp
  (autoload 'global-centered-cursor-mode "centered-cursor-mode")
  (bind-keys ("M-L" . global-centered-cursor-mode))
#+END_SRC
* editing
enhanced behavior.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("C--". undo-tree-undo))
  (global-undo-tree-mode 1)
  (delight 'undo-tree-mode nil 'undo-tree)

  (bind-keys ("C-M-y" . browse-kill-ring))

  (bind-keys ("M-z" . zzz-to-char))

  (bind-keys ("M-u" . fix-word-upcase)
             ("M-l" . fix-word-downcase)
             ("M-c" . fix-word-capitalize))

  (cset 'same-window-buffer-names '("*Buffer List*")
        'indent-tabs-mode         nil
        'fill-column              81)
#+END_SRC
extra convenience.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("M-F" . vimish-fold-toggle)
             ("M-J" . vimish-fold-avy)
             ("M-K" . vimish-fold-delete))

  (bind-keys ("<M-left>"  . drag-stuff-left)
             ("<M-right>" . drag-stuff-right)
             ("<M-down>"  . drag-stuff-down)
             ("<M-up>"    . drag-stuff-up))

  (bind-keys ("M-I" . global-aggressive-indent-mode)
             ("C-j" . newline-and-indent))
  (global-aggressive-indent-mode 1)
  (delight 'aggressive-indent-mode " i" 'aggressive-indent)

  (bind-keys ("M-D" . global-hungry-delete-mode))
  (global-hungry-delete-mode 1)
  (delight 'hungry-delete-mode " d" 'hungry-delete)

  (global-whitespace-cleanup-mode 1)
  (delight 'whitespace-cleanup-mode nil 'whitespace-cleanup-mode)
#+END_SRC
structured editing.
#+BEGIN_SRC emacs-lisp
  (require 'smartparens-config)
  (smartparens-global-mode 1)
  (delight 'smartparens-mode nil 'smartparens)
  (bind-keys :map smartparens-mode-map
             ("C-M-a"   . sp-beginning-of-sexp)
             ("C-M-b"   . sp-backward-sexp)
             ("C-M-d"   . sp-down-sexp)
             ("C-M-e"   . sp-end-of-sexp)
             ("C-M-f"   . sp-forward-sexp)
             ("C-M-h"   . sp-raise-sexp)
             ("C-M-j"   . sp-splice-sexp)
             ("C-M-k"   . sp-kill-sexp)
             ("C-M-n"   . sp-add-to-next-sexp)
             ("C-M-o"   . sp-split-sexp)
             ("C-M-p"   . sp-indent-adjust-sexp)
             ("C-M-q"   . sp-rewrap-sexp)
             ("C-M-t"   . sp-transpose-sexp)
             ("C-M-u"   . sp-backward-up-sexp)
             ("C-M-w"   . sp-copy-sexp)
             ("C-d"     . sp-delete-char)
             ("C-k"     . sp-kill-hybrid-sexp)
             ("C-x C-t" . sp-transpose-hybrid-sexp)
             ("DEL"     . sp-backward-delete-char)
             ("M-("     . sp-splice-sexp-killing-backward)
             ("M-)"     . sp-splice-sexp-killing-forward)
             ("M-*"     . sp-convolute-sexp)
             ("M-+"     . sp-join-sexp)
             ("M-DEL"   . sp-backward-kill-word)
             ("M-["     . sp-absorb-sexp)
             ("M-]"     . sp-forward-slurp-sexp)
             ("M-d"     . sp-kill-word)
             ("M-n"     . sp-next-sexp)
             ("M-p"     . sp-previous-sexp)
             ("M-{"     . sp-extract-before-sexp)
             ("M-}"     . sp-dedent-adjust-sexp))

  (show-smartparens-global-mode 1)
  (set-face-attribute 'sp-show-pair-match-face    nil :background "#181818" :foreground "#A41210" :weight 'bold)
  (set-face-attribute 'sp-show-pair-mismatch-face nil :background "#161616" :foreground "#003B6F" :weight 'black)
#+END_SRC
batched editing.
#+BEGIN_SRC emacs-lisp
  (when (display-graphic-p)
    (with-eval-after-load 'multiple-cursors
      (set-face-attribute 'mc/cursor-bar-face nil :background "#DAA520" :foreground "#242424")))

  (bind-keys ("M-M"   . mc/mark-more-like-this-extended)
             ("C-M-%" . vr/query-replace))
#+END_SRC
region editing.
#+BEGIN_SRC emacs-lisp
  (require 'region-bindings-mode)
  (region-bindings-mode-enable)
  (bind-keys ("M-h" . er/expand-region)
             :map region-bindings-mode-map
             ("b" . comment-box)
             ("d" . delete-region)
             ("f" . vimish-fold)
             ("g" . keyboard-quit)
             ("i" . indent-region)
             ("k" . kill-region)
             ("l" . downcase-region)
             ("m" . mc/mark-all-in-region)
             ("M" . vr/mc-mark)
             ("n" . mc/edit-lines)
             ("r" . replace-string)
             ("R" . vr/replace)
             ("u" . upcase-region)
             ("w" . kill-ring-save)
             (";" . comment-or-uncomment-region)
             ("$" . flyspell-region))
#+END_SRC
auto-completion.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("M-/" . hippie-expand))
  (with-eval-after-load 'hippie-exp
    (cset 'hippie-expand-try-functions-list
          '(try-complete-file-name-partially
            try-complete-file-name
            try-expand-all-abbrevs
            try-expand-dabbrev
            try-expand-dabbrev-visible
            try-expand-dabbrev-all-buffers
            try-expand-dabbrev-from-kill
            try-expand-whole-kill
            try-complete-lisp-symbol-partially
            try-complete-lisp-symbol)))

  (global-company-mode 1)
  (company-quickhelp-mode 1)
  (delight 'company-mode nil 'company)
  (bind-keys ("C-M-i" . company-complete)
             :map company-active-map
             ("M-h" . company-quickhelp-manual-begin))
  (unbind-keys company-active-map "TAB" "<tab>")
  (cset 'company-idle-delay                0.2
        'company-minimum-prefix-length     2
        'company-tooltip-align-annotations t
        'company-selection-wrap-around     t
        'company-quickhelp-delay           nil)
#+END_SRC
snippet.
#+BEGIN_SRC emacs-lisp
  (yas-global-mode 1)
  (delight 'yas-minor-mode nil 'yasnippet)
#+END_SRC
error check.
#+BEGIN_SRC emacs-lisp
  (bind-keys ("M-$" . flyspell-mode))
  (with-eval-after-load 'flyspell
    (delight 'flyspell-mode " $" 'flyspell)
    (bind-keys :map flyspell-mode-map ("C-;" . flyspell-correct-word-before-point)))

  (with-eval-after-load 'flycheck
    (flycheck-pos-tip-mode))
  (add-hooks 'shell-mode-hook #'flycheck-mode)
#+END_SRC
* clojure
#+BEGIN_SRC emacs-lisp
  (add-hooks 'clojure-mode-hook    #'eldoc-mode #'clj-refactor-mode)
  (add-hooks 'cider-repl-mode-hook #'eldoc-mode #'clj-refactor-mode)

  (bind-keys ("M-S" . cider-scratch))

  (with-eval-after-load 'cider
    (bind-keys :map cider-mode-map
               ("M-RET" . cider-eval-last-sexp)
               ("C-M-x" . cider-eval-defun-at-point)
               ("C-M-z" . cider-eval-region))

    (cset 'nrepl-hide-special-buffers          t
          'cider-font-lock-dynamically         t
          'cider-prefer-local-resources        t
          'cider-allow-jack-in-without-project t
          'cider-doc-xref-regexp               "\\[\\[\\(.*?\\)\\]\\]"
          'cider-repl-history-file             (f-expand "cider-history" user-emacs-directory)))

  (with-eval-after-load 'clj-refactor
    (cljr-add-keybindings-with-prefix "M-R")
    (cset 'cljr-suppress-middleware-warnings t))
#+END_SRC
* scheme
#+BEGIN_SRC emacs-lisp
  (add-hooks 'geiser-mode-hook #'flycheck-mode)
  (with-eval-after-load 'geiser
    (bind-keys :map scheme-mode-map
               ("M-RET" . geiser-eval-last-sexp)
               ("C-M-x" . geiser-eval-definition)
               ("C-M-z" . geiser-eval-region))
    (cset 'geiser-active-implementations '(chez)))
#+END_SRC
* prolog
#+BEGIN_SRC emacs-lisp
  (push '("\\.pl$" . prolog-mode) auto-mode-alist)
  (with-eval-after-load 'prolog
    (bind-keys :map prolog-mode-map ("M-RET" . ediprolog-dwim)))
#+END_SRC
* idris
#+BEGIN_SRC emacs-lisp
  (add-hooks 'idris-mode-hook 'eldoc-mode-hook (-partial #'aggressive-indent-mode -1))

  (with-eval-after-load 'idris-mode
    (bind-keys :map idris-mode-map
               ("M-RET"   . idris-case-dwim)
               ("C-M-x"   . idris-add-clause)
               ("C-M-z"   . idris-proof-search)
               ("C-c C-q" . idris-quit)))
#+END_SRC
* rust
#+BEGIN_SRC emacs-lisp
  (add-hooks 'rust-mode-hook
             #'eldoc-mode
             #'flycheck-mode
             #'flycheck-rust-setup
             #'cargo-minor-mode
             #'racer-mode)

  (with-eval-after-load 'rust-mode
    (cset 'racer-rust-src-path
          (funcall (if (equal 'ns window-system)
                       #'exec-path-from-shell-getenv
                     #'getenv)
                   "RUST_SRC_PATH")))
#+END_SRC
* python
#+BEGIN_SRC emacs-lisp
  (add-hooks 'python-mode-hook
             #'elpy-mode
             (-partial #'highlight-indentation-mode -1)
             (-partial #'aggressive-indent-mode -1))

  (with-eval-after-load 'python-mode
    (bind-keys :map python-mode-map
               ("C-M-x" . python-shell-send-defun)
               ("C-M-z" . python-shell-send-region))
    (elpy-enable))
#+END_SRC
* javascript
#+BEGIN_SRC emacs-lisp
  (push '("\\.js\\'" . js2-mode) auto-mode-alist)

  (add-hooks 'js2-mode-hook  #'flycheck-mode)
  (add-hooks 'css-mode-hook  #'flycheck-mode)
  (add-hooks 'html-mode-hook #'flycheck-mode)
#+END_SRC
* r
#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'ess
    (bind-keys :map ess-mode-map
               ("M-RET" . ess-eval-line)
               ("C-M-x" . ess-eval-function-or-paragraph)
               ("C-M-z" . ess-eval-region)))
#+END_SRC
* markdown
#+BEGIN_SRC emacs-lisp
  (push '("README\\.md\\'" . gfm-mode)      auto-mode-alist)
  (push '("\\.[Rr]md\\'"   . markdown-mode) auto-mode-alist)

  (add-hooks 'markdown-mode-hook #'flyspell-mode #'flycheck-mode)

  (with-eval-after-load 'markdown-mode
    (cset 'markdown-enable-math t))
#+END_SRC
* tex
#+BEGIN_SRC emacs-lisp
  (add-hooks 'LaTeX-mode-hook
             #'flyspell-mode
             #'flycheck-mode
             #'LaTeX-math-mode
             #'latex-preview-pane-enable
             #'turn-on-cdlatex
             #'turn-on-reftex
             (-partial #'set 'TeX-command-default "xelatexmk"))

  (with-eval-after-load 'tex
    (with-eval-after-load 'company
      (company-auctex-init))
    (unbind-keys cdlatex-mode-map "<" "(" "[" "{")
    (push '("xelatexmk"
            "latexmk -pdf -pdflatex=\"xelatex -interaction=nonstopmode -shell-escape -synctex=1\" %s"
            TeX-run-TeX nil t :help "run xelatexmk on file")
          TeX-command-list)
    ;; Skim -> Preferences -> Sync; CMD + shift + click in the pdf file for jumping to source
    (push '("skim" "/Applications/Skim.app/Contents/SharedSupport/displayline -b %n %o %b")
          TeX-view-program-list)
    (push '(output-pdf "skim") TeX-view-program-selection)
    (server-start)
    (cset 'TeX-engine              'xetex
          'TeX-auto-save           t
          'TeX-parse-self          t
          'reftex-plug-into-AUCTeX t))
#+END_SRC
* org
#+BEGIN_SRC emacs-lisp
  (add-hooks 'org-mode-hook #'flyspell-mode #'turn-on-org-cdlatex)

  (bind-keys ("M-A" . org-agenda))

  (with-eval-after-load 'org
    (unbind-keys org-mode-map "C-'" "M-h")
    (cset 'org-directory                          "~/sotha_sil/emacs/org"
          'org-agenda-files                       "~/sotha_sil/emacs/org/agenda-files"
          'org-archive-location                   "~/sotha_sil/emacs/org/archive.org::"
          'org-log-done                           'time
          'org-latex-create-formula-image-program 'imagemagick
          'org-latex-listings                     'minted
          'org-src-fontify-natively               t
          'org-latex-default-packages-alist
          '(("" "fontspec" t)
            ("" "graphicx" t)
            ("" "longtable" nil)
            ("" "float" nil)
            ("" "wrapfig" nil)
            ("" "rotating" nil)
            ("normalem" "ulem" t)
            ("" "amsmath" t)
            ("" "hyperref" nil))))
#+END_SRC
* summary

- dead on terminal: []
- forced translate: [target]
- override default: +old+ ~new~

|         | C-                                | M-                                                              | C-M-                                        |
|---------+-----------------------------------+-----------------------------------------------------------------+---------------------------------------------|
| DEL     | [DEL]                             | ~sp-backward-kill-word~                    +backward-kill-word+ | [C-M-h]                                     |
| TAB     | [TAB]                             | [C-M-i]                                                         | [C-M-i]                                     |
| RET     | [RET]                             | ~eval-last-sexp~                                                | [M-RET]                                     |
| SPC     | [C-@]                             | just-one-space                                                  | [M-SPC]                                     |
| <up>    | <up>                              | ~drag-stuff-up~                                                 | [ESC <up>]                                  |
| <left>  | ~[]~                  +left-word+ | ~drag-stuff-left~                               +backward-word+ | [ESC <left>]                                |
| <down>  | <down>                            | ~drag-stuff-down~                                               | [ESC <down>]                                |
| <right> | ~[]~                 +right-word+ | ~drag-stuff-right~                               +forward-word+ | [ESC <right>]                               |
|---------+-----------------------------------+-----------------------------------------------------------------+---------------------------------------------|
| 1       | []                                | digit-argument 1                                                | [M-1]                                       |
| 2       | []                                | digit-argument 2                                                | [M-2]                                       |
| 3       | []                                | digit-argument 3                                                | [M-3]                                       |
| 4       | []                                | digit-argument 4                                                | [M-4]                                       |
| 5       | []                                | digit-argument 5                                                | [M-5]                                       |
| 6       | []                                | digit-argument 6                                                | [M-6]                                       |
| 7       | []                                | digit-argument 7                                                | [M-7]                                       |
| 8       | []                                | digit-argument 8                                                | [M-8]                                       |
| 9       | []                                | digit-argument 9                                                | [M-9]                                       |
| 0       | []                                | digit-argument 0                                                | [M-0]                                       |
|---------+-----------------------------------+-----------------------------------------------------------------+---------------------------------------------|
| !       | []                                | shell-command                                                   |                                             |
| @       | set-mark-command                  | +mark-word+                                                     |                                             |
| #       | []                                | ~linum-mode~                                                    |                                             |
| $       | []                                | ~flyspell-mode~                                   +ispell-word+ |                                             |
| %       | []                                | query-replace                                                   | ~vr/query-replace~   +query-replace-regexp+ |
| ^       |                                   | delete-indentation                                              |                                             |
| &       | []                                | async-shell-command                                             |                                             |
| *       | []                                | ~sp-raise-sexp~                                                 |                                             |
| (       | []                                | ~sp-splice-sexp-killing-backward~          +insert-parentheses+ |                                             |
| )       | []                                | ~sp-splice-sexp-killing-forward~ +move-past-close-and-reindent+ |                                             |
|---------+-----------------------------------+-----------------------------------------------------------------+---------------------------------------------|
| -       | [C-_]                             | negative-argument                                               | [C-M-_]                                     |
| =       | []                                | count-words-region                                              | [M-=]                                       |
| [       | [ESC-]                            | ~sp-absorb-sexp~                                                | ~sp-forward-slurp-sexp~                     |
| ]       | abort-recursive-edit              | ~sp-extract-before-sexp~                                        | ~sp-dedent-adjust-sexp~                     |
| ;       | []                                | comment-dwim                                                    | [M-;]                                       |
| '       | []                                | ~avy-goto-char-2~                          +abbrev-prefix-mark+ | [M-']                                       |
| \       | toggle-input-method               | delete-horizontal-space                                         | indent-region                               |
| `       | []                                | tmm-menubar                                                     | [M-`]                                       |
| ,       | []                                | xref-pop-marker-stack                                           | [M-,]                                       |
| .       | []                                | xref-find-definitions                                           | [M-.]                                       |
| /       | []                                | ~hippie-expand~                                +dabbrev-expand+ | [M-/]                                       |
|---------+-----------------------------------+-----------------------------------------------------------------+---------------------------------------------|
| _       | ~undo-tree-undo~           +undo+ | ~undo-tree-redo~                                                | ~toggle-truncate-lines~ +negative-argument+ |
| +       | []                                | ~sp-join-sexp~                                                  |                                             |
| {       | [C-[]                             | backward-paragraph                                              |                                             |
| }       | [C-]]                             | forward-paragraph                                               |                                             |
| :       | []                                | eval-expression                                                 |                                             |
| "       | []                                | ~avy-pop-mark~                                                  |                                             |
| \mid    | [C-\]                             | shell-command-on-region                                         |                                             |
| ~       | []                                | not-modified                                                    |                                             |
| <       | []                                | beginning-of-buffer                                             |                                             |
| >       | []                                | end-of-buffer                                                   |                                             |
| ?       | []                                | xref-find-regerences                                            |                                             |
|---------+-----------------------------------+-----------------------------------------------------------------+---------------------------------------------|
| a       | move-beginning-of-line            | backward-sentence                                               | ~sp-beginning-of-sexp~ +beginning-of-defun+ |
| b       | backward-char                     | backward-word                                                   | ~sp-backward-sexp~          +backward-sexp+ |
| c       | [C-c-]                            | ~fix-word-capitalize~                         +capitalize-word+ | exit-recursive-edit                         |
| d       | ~sp-delete-char~    +delete-char+ | ~sp-kill-word~                                      +kill-word+ | ~sp-down-sexp~                  +down-list+ |
| e       | move-end-of-line                  | forward-sentence                                                | ~sp-end-of-sexp~             +end-of-defun+ |
| f       | forward-char                      | forward-word                                                    | ~sp-forward-sexp~            +forward-sexp+ |
| g       | keyboard-quit                     | [M-g-]                                                          | []                                          |
| h       | [C-h-]                            | ~er/expand-region~                             +mark-paragraph+ | ~sp-raise-sexp~                +mark-defun+ |
| i       | [TAB]                             | tab-to-tab-stop                                                 | ~company-complete~    +completion-at-point+ |
| j       | newline-and-indent                | indent-new-comment-line                                         | ~sp-splice-sexp~ +indent-new-comment-line+  |
| k       | ~sp-kill-hybrid-sexp~ +kill-line+ | kill-sentence                                                   | ~sp-kill-sexp~                  +kill-sexp+ |
| l       | recenter-top-bottom               | ~fix-word-downcase~                             +downcase-word+ | reposition-window                           |
| m       | [RET]                             | back-to-indentation                                             | [M-RET]                                     |
| n       | next-line                         | ~sp-next-sexp~                                                  | ~sp-add-to-next-sexp~        +forward-list+ |
| o       | open-line                         | [M-o-]                                                          | ~sp-split-sexp~                +split-line+ |
| p       | previous-line                     | ~sp-previous-sexp~                                              | ~sp-indent-adjust-sexp~     +backward-list+ |
| q       | quoted-insert                     | fill-paragraph                                                  | ~sp-rewrap-sexp~           +indent-pp-sexp+ |
| r       | isearch-backward                  | move-to-window-line-top-bottom                                  | isearch-backward-regexp                     |
| s       | ~swiper~        +isearch-forward+ | [M-s-]                                                          | isearch-forward-regexp                      |
| t       | transpose-chars                   | transpose-words                                                 | ~sp-transpose-sexp~       +transpose-sexps+ |
| u       | universal-argument                | ~fix-word-upcase~                                 +upcase-word+ | ~sp-backward-up-sexp~    +backward-up-list+ |
| v       | scroll-up-command                 | scroll-down-command                                             | scroll-other-window                         |
| w       | kill-region                       | kill-ring-save                                                  | ~sp-copy-sexp~           +append-next-kill+ |
| x       | [C-x-]                            | ~counsel-M-x~                        +execute-extended-command+ | eval-defun                                  |
| y       | yank                              | yank-pop                                                        | ~browse-kill-ring~                          |
| z       | suspend-frame                     | ~zzz-to-char~                                     +zap-to-char+ | eval-region                                 |

on text terminals, shift does not work with ctrl.

|   | M-                                |
|---+-----------------------------------|
| A | ~org-agenda~                      |
| B |                                   |
| C |                                   |
| D | ~global-hungry-delete-mode~       |
| E |                                   |
| F | ~vimish-fold-toggle~              |
| G | ~magit-status~                    |
| H |                                   |
| I | ~global-aggressive-indent-mode~   |
| J | ~vimish-fold-avy~                 |
| K | ~vimish-fold-delete~              |
| L | ~global-centered-cursor-mode~     |
| M | ~mc/mark-more-like-this-extended~ |
| N |                                   |
| O |                                   |
| P |                                   |
| Q | ~suggest~                         |
| R | ~cljr~                            |
| S | ~cider-scratch~                   |
| T |                                   |
| U |                                   |
| V |                                   |
| W |                                   |
| X |                                   |
| Y |                                   |
| Z |                                   |

others, incomplete.

| C-h i     | info                                                      |
| C-h r     | info-emacs-manual                                         |
| C-x C-SPC | pop-global-mark                                           |
| C-x C-t   | ~sp-transpose-hybrid-sexp~              +transpose-lines+ |
| C-x f     | set-fill-column                                           |
| C-x o     | ~ace-window~                               +other-window+ |
| C-x u     | ~undo-tree-visualize~                                     |
| C-x z     | repeat                                                    |
| DEL       | ~sp-backward-delete-char~ +backward-delete-char-untabify+ |
| M-g g     | ~avy-goto-line~                               +goto-line+ |
